 create table contract (
        id number not null,
        consortium_flag boolean not null,
        contract_number bigint not null,
        primary key (id)
    )
create table person (
        id bigint generated by default as identity,
        name varchar(255),
        surname varchar(255),
        primary key (id)
    ) 
create sequence CONTRACT_ID_SEQ