CREATE TABLE ITEM (ID INTEGER, DESCRIPTION VARCHAR, ITEM_VALUE FLOAT);

INSERT INTO ITEM (ID, DESCRIPTION, ITEM_VALUE) VALUES (1, 'Item 1', 10.5);
INSERT INTO ITEM (ID, DESCRIPTION, ITEM_VALUE) VALUES (2, 'Item 2', 6.1);
INSERT INTO ITEM (ID, DESCRIPTION, ITEM_VALUE) VALUES (3, 'Item 3', 14.3);
INSERT INTO ITEM (ID, DESCRIPTION, ITEM_VALUE) VALUES (4, 'Item 4', 20.7);
INSERT INTO ITEM (ID, DESCRIPTION, ITEM_VALUE) VALUES (5, 'Item 5', 25.9);